### ISSUE TITLE
[Flex] Phase 1 Project Review Guidelines

### ISSUE THREAD

**Issue by tloughrist** [learn-co-curriculum/phase-1-project-review-guidelines#2]
Guidelines indicate project components should be submitted via ScheduleOnce. The software is no longer called ScheduleOnce; it is now  OnceHub.

It's worth pointing out, however, that students are not necessarily familiar with either of those names, since those names do not appear anywhere on the submission page (except in the URL).

**Comment by lizbur10** [comment]
Thanks @tloughrist!
